# -*- coding: utf-8 -*-
"""Projeto_Messias.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ti2fK5cISlI3oIX8WNAudf-8UbkLnOE9
"""

#Jesus e Luana

import os
import requests

!pip install deep_translator

from deep_translator import GoogleTranslator

os.system( 'cls' if os.name == 'nt' else 'clear' )

Condicao = True ##### Variavel de condicao do laço
dicio = dict() #### Para guardar os conselhos com seu id
arquivo = open( "Conselhos.txt", "w")
posicao = 0  ### variavel para acompanharmos a posicao do cursor no arquivo


Divisoria = "   ------------------------------------------------------------------   \n\n"

#########
while(Condicao):

  print( "----- Bom dia ! Seja bem vindo à Cachaçaria do Seu Zé ! ! -------- \n")
  print( "----- Depois de uma boa nada melhor do querer buscar orientação na vida não é mesmo -----!? :) :)\n")
  print( "----- Diga quantos conselhos deseja -------\n ")

#########################################################################################

  qtde = int( input('\n\n') )

  SOLICITACAO_DE_CONSELHO (qtde)

  #########

  print("Deseja ver novamente estes conselhos ? \n\n ")

  s = input('\n')

  if(s.upper() == 'SIM'):

    EXIBIR_CONSELHOS()

  #########

  print("Deseja traduzir estes conselhos ? \n")

  s = input('\n')

  if(s.upper() == 'SIM') :

    TRADUZIR_CONSELHOS()

  ###########

  print("Deseja resgatar algum conselho ? \n")

  s = input('\n')

  print("Digite o id \n")

  ID = int( input('\n') )

  if(s.upper() == 'SIM') :

    RESGATAR_CONSELHOS( ID )

  #############

  print("Deseja pedir mais conselhos ? \n\n" )

  s = input('\n')

  if(s.upper() == 'SIM') :


    arquivo = open( 'Conselhos.txt' , 'a') #reabrindo o arquivo em modo anexo
    continue

  else:

    arquivo.close()
    Condicao = False


###################
print("\ Deseja ver todos os conselhos ? \n ")

s = input('\n')

if(s.upper() == 'SIM') :

  arquivo = open("Conselhos.txt", "r")

  for linha in arquivo.readlines() :

     print(linha)

def SOLICITACAO_DE_CONSELHO ( qtde):



    arquivo.write( Divisoria )

    contar = 0

    posicao = arquivo.tell()
    #########

    while(contar < qtde):

    ###### Fazendo o pedido da api de conselhos

      pedido_url = "https://api.adviceslip.com/advice"

      resposta = requests.get(pedido_url)

      id  =  resposta.json()['slip']

    ########## Registrando no arquivo e no dicionario


      arquivo.write( str(id ["id"]) + '  ----  ' + id ["advice"] + '\n' )  ##Registrando no arquivo texto

      dicio[ id ["id"]] = id["advice"]  ##registrando no dicionario

    ########## Imprimindo o Conselho

      print(id["advice"].center(10) + '\n' )

      contar += 1


  ###################################################################
    posicao = arquivo.tell()

    arquivo.close()

  #############

def EXIBIR_CONSELHOS():

  arq = open( "Conselhos.txt" , 'r')

  arq.seek( posicao )
  ####
  for linha in arq.readlines():

    print(linha )

####
  arq.close()

def  TRADUZIR_CONSELHOS() :

  arquivo = open('Conselhos.txt' , 'r')

  #Posicionamento cursor nos conselhos atuais

  arquivo.seek( posicao )

  arquivo.readline()
  arquivo.readline()
  #####

  Nosso_Tradutor = GoogleTranslator( source = 'en' , target = 'pt')


  #####
  for frase in arquivo.readlines() :

    traducao = Nosso_Tradutor.translate( frase )

    print( 'Frase : ' + frase + '\n' + 'Traducao : ' + traducao + '\n' )

    ####

    if ( frase == Divisoria  ) :

      break

def  RESGATAR_CONSELHOS( id ) :

  try :

    conselho = dicio[ id ]
    print( f"O conselho requerido e {conselho} \n" )

  except:

    raise ValueError ({ f" Nao existe esta id { id } no dicionario \n"})